### ISSUE TITLE
Doesn't work on Redmine 3.4

### ISSUE THREAD

**Issue by vinznsk** [x3ro/redmine_amazon_s3#15]
Hello,

I'm trying to install this plugin on Redmine 3.4, but it doesn't work. I don't see any errors, just redmine continues upload files to local storage.

ActionController::RoutingError (No route matches [GET] "/plugin_assets/amazon_s3/javascripts/redmine_s3.js"):
  actionpack (4.2.8) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.8) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.8) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.8) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  actionpack (4.2.8) lib/action_dispatch/middleware/static.rb:120:in `call'

**Comment by vinznsk** [comment]
Found the problem. I forgot to rename the main folder to "amazon_s3" it was "redmine_amazon_s3" so js didn't work.
